---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-oauth-playground-backend-config
data:
  application.properties: |
    quarkus.otel.exporter.otlp.endpoint=http://otel-collector.observability.svc:4317
    quarkus.oidc.auth-server-url=https://sso.apps.ocp4.jnyilimb.eu/realms/demo
---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-oauth-playground-backend-secret
stringData:
  application.properties: |
    quarkus.oidc.credentials.secret=ihqZiCLvTse1advVzPT15s1Gev3XFS93
type: Opaque