apiVersion: v1
kind: Service
metadata:
  name: oauth-playground-frontend
  labels:
    app: oauth-playground-frontend
    app.kubernetes.io/name: oauth-playground-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: rhbk-playground
spec:
  selector:
    app: oauth-playground-frontend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
