apiVersion: v1
kind: Service
metadata:
  name: nodejs-oauth-playground-frontend
  labels:
    app: nodejs-oauth-playground-frontend
    app.kubernetes.io/name: nodejs-oauth-playground-frontend
    app.kubernetes.io/component: nodejs-frontend
    app.kubernetes.io/part-of: nodejs-playground
spec:
  selector:
    app: nodejs-oauth-playground-frontend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
