apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-playground-backend-config
  labels:
    app: oauth-playground-backend
    app.kubernetes.io/name: oauth-playground-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: rhbk-playground
data:
  keycloak.json: |
    {
      "realm": "demo",
      "auth-server-url": "https://sso.apps.example.com/",
      "ssl-required": "all",
      "resource": "oauth-backend",
      "verify-token-audience": true,
      "credentials": {},
      "use-resource-role-mappings": true,
      "confidential-port": 0
    }
