apiVersion: v1
kind: Service
metadata:
  name: oauth-playground-backend
  labels:
    app: oauth-playground-backend
    app.kubernetes.io/name: oauth-playground-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: rhbk-playground
spec:
  selector:
    app: oauth-playground-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
