apiVersion: v1
kind: Service
metadata:
  name: nodejs-oauth-playground-backend
  labels:
    app: nodejs-oauth-playground-backend
    app.kubernetes.io/name: nodejs-oauth-playground-backend
    app.kubernetes.io/component: nodejs-backend
    app.kubernetes.io/part-of: nodejs-playground
spec:
  selector:
    app: nodejs-oauth-playground-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
