---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-oidc-playground-config
data:
  application.properties: |
    quarkus.otel.exporter.otlp.endpoint=http://otel-collector.observability.svc:4317
    keycloak.url=https://sso.apps.ocp4.jnyilimb.eu
    keycloak.issuer=https://sso.apps.ocp4.jnyilimb.eu/realms/demo
