apiVersion: v1
kind: Service
metadata:
  name: oidc-playground
  labels:
    app: oidc-playground
    app.kubernetes.io/name: oidc-playground
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: rhbk-playground
spec:
  selector:
    app: oidc-playground
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
